# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate numpy-dev
#
name: numpy-dev
channels:
  - conda-forge
dependencies:
  - python=3.9 #need to pin to avoid issues with builds
  - cython
  - compilers
  - openblas
  - nomkl
  - setuptools=59.2.0
  # For testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  # For type annotations
  - mypy=0.942
  # For building docs
  - sphinx=4.5.0
  - sphinx-panels
  - numpydoc=1.3.1
  - ipython
  - scipy
  - pandas
  - matplotlib
  - pydata-sphinx-theme=0.8.1
  # NOTE: breathe 4.33.0 collides with sphinx.ext.graphviz
  - breathe!=4.33.0
  # For linting
  - pycodestyle=2.7.0
  - gitpython
  # Used in some tests
  - cffi
  - pytz
